### PR TITLE
Add open to expose yojson functions used in derives

### LINKED ISSUE #200: opam install error
Hi !
I have a compilation error when installing jupyter through opam.
Environment : 
> Ubuntu 22.04 through WSL, Windows 11

Steps to reproduce :
> In a fresh switch `opam switch create 4.14.1`, do `opam install jupyter`

The compilation fails and the error is as follows :
```
[ERROR] The compilation of jupyter.2.8.2 failed at "dune build -p jupyter -j 15".

#=== ERROR while compiling jupyter.2.8.2 ======================================#
# context     2.1.2 | linux/x86_64 | ocaml-base-compiler.4.14.1 | https://opam.ocaml.org#6ed4e23f
# path        ~/.opam/4.14.1/.opam-switch/build/jupyter.2.8.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p jupyter -j 15
# exit-code   1
# env-file    ~/.opam/log/jupyter-24386-bd5071.env
# output-file ~/.opam/log/jupyter-24386-bd5071.out
### output ###
# [...]
# File "src/core/stdin.ml", line 29, characters 19-25:
# 29 |     stdin_prompt : string [@key "prompt"];
#                         ^^^^^^
# Error: Unbound value string_of_yojson
# (cd _build/default && /home/tippexls/.opam/4.14.1/bin/ocamlc.opt -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58-66 -safe-string -strict-sequence -strict-formats -short-paths -g -bin-annot -I src/core/.jupyter.objs/byte -I /home/tippexls/.opam/4.14.1/lib/ppx_yojson_conv_lib -I /home/tippexls/.opam/4.14.1/lib/seq -I /home/tippexls/.opam/4.14.1/lib/uuidm -I /home/tippexls/.opam/4.14.1/lib/yojson [...]
# File "src/core/ansiCode.pp.ml", line 1:
# Warning 70 [missing-mli]: Cannot find interface file.
# (cd _build/default && /home/tippexls/.opam/4.14.1/bin/ocamlc.opt -w A-4-31-33-34-39-41-42-43-44-45-48-49-50-58-66 -safe-string -strict-sequence -strict-formats -short-paths -g -bin-annot -I src/core/.jupyter.objs/byte -I /home/tippexls/.opam/4.14.1/lib/ppx_yojson_conv_lib -I /home/tippexls/.opam/4.14.1/lib/seq -I /home/tippexls/.opam/4.14.1/lib/uuidm -I /home/tippexls/.opam/4.14.1/lib/yojson [...]
# File "src/core/comm.ml", line 26, characters 25-31:
# 26 |     comm_target : string option [@key "target_name"] [@default None];
#                               ^^^^^^
# Error: Unbound value option_of_yojson
```

I believe the issue appeared when updating `ppx_yojson_conv` from v0.15.1 to v0.16.0. Maybe it is linked to https://github.com/janestreet/ppx_yojson_conv/issues/18#issue-1758439838 ?

Thanks for your work on this.

### PR DESCRIPTION
**Pull request by mt-caret**
Fixes https://github.com/akabe/ocaml-jupyter/issues/200.

I tried running some tests as best as I can but I'm not sure if the test failures I'm getting are relevant to https://github.com/akabe/ocaml-jupyter/issues/200.

### CODE REVIEW

**Comment by akabe** [comment]
@mt-caret 
First and foremost, let me express our gratitude for your donation. It means a lot to me and keeps me motivated to continue our work.

Also, I wanted to say a thank you for helping me fix the problem that I had left untouched for years.
Your patch looks good, but an integration test related to `ppx_yojson_conv` fails:

```
2023-08-09T08:39:07 [INFO] SEND: HMAC=d07f878740bfba2dcea2c2a4dc741c3eaafd5358e3883bcc6a4682def75c80e2; header={"msg_id":"3e80dbb2-de6d-4ca0-a909-530860a8eb3e","msg_type":"error","session":"6f36d72f-bf78e6d077b8440405e80146","date":"2023-08-09T08:39:07.8911Z","username":"runner","version":"5.3"}; parent={"msg_id":"6f36d72f-bf78e6d077b8440405e80146_27949_2","msg_type":"execute_request","session":"6f36d72f-bf78e6d077b8440405e80146","date":"2023-08-09T08:39:07.770278Z","username":"runner","version":"5.3"}; content={"ename":"error","evalue":"compile_error","traceback":["File \"[1]\", line 3, characters 17-20:\n3 | type t = { foo : int; baz : string; } [@@deriving yojson]\n                     ^^^\nError: Unbound value int_of_yojson\n"]}; metadata={}
```

cf. https://github.com/akabe/ocaml-jupyter/actions/runs/5795450506/job/15740046501?pr=201#step:13:213

Could you add `open Ppx_yojson_conv_lib.Yojson_conv.Primitives` to the file [tests/integration/ppx.ipynb](https://github.com/akabe/ocaml-jupyter/blob/master/tests/integration/ppx.ipynb)?

**Comment by mt-caret** [comment]
> First and foremost, let me express our gratitude for your donation. It means a lot to me and keeps me motivated to continue our work.

Thank *you* for working on this amazing project; I'm impressed by how well this works, and sponsoring your work is the very least I can do :)

> Could you add open Ppx_yojson_conv_lib.Yojson_conv.Primitives to the file [tests/integration/ppx.ipynb](https://github.com/akabe/ocaml-jupyter/blob/master/tests/integration/ppx.ipynb)?

Done!

**Comment by akabe** [comment]
Thank you so much!

**Comment by akabe** [comment]
@mt-caret 
In case you're interested, I have the option to add your icon and a web page link to the [README#Sponsors](https://github.com/akabe/ocaml-jupyter#sponsors). Please let me know your thoughts on how you'd like to proceed.

**Comment by mt-caret** [comment]
Thanks so much for the offer, but no thanks; my sponsorships are all private, and I'm not very interested in advertising my sponsorships :)
