### PR TITLE
Fix for ocaml 4.09

### LINKED ISSUE #136: doesn't build on 4.09
I get this error:

```
# File "compat.cppo.ml", line 32, characters 7-45:
# Error: Unbound module Pparse.ImplementationHooks
```

### PR DESCRIPTION
**Pull request by mseri**
Which dropped support for compiler hooks and plugins. Should resolve https://github.com/akabe/ocaml-jupyter/issues/136

Locally only one test fails due to improved error messages in 4.09.

Also `ppx_deriving_yojson` seems to be required for some of the tests to build with recent dune/ppx_deriving_yojson, so I have updated the dune files.

### CODE REVIEW

**Comment by akabe** [comment]
Thanks a lot. Your patch seems good, while CI is wrong maybe. I will fix it.

**Comment by akabe** [comment]
I fixed CI #138. Please merge or rebase the current master to this branch.

**Comment by mseri** [comment]
Done, thanks!

**Comment by akabe** [comment]
Your patch works fine in my environment. I will release a new version. Thank you!
