### ISSUE TITLE
doesn't build on 4.09

### ISSUE THREAD

**Issue by ghennequin** [akabe/ocaml-jupyter#136]
I get this error:

```
# File "compat.cppo.ml", line 32, characters 7-45:
# Error: Unbound module Pparse.ImplementationHooks
```

**Comment by mseri** [comment]
It is due to `https://github.com/ocaml/ocaml/pull/2276`. I have a patch but I don't know how correct is it. I'll send a PR

**Comment by akabe** [comment]
v2.6.1 supports OCaml 4.09 thanks to @mseri ! It has been already released to opam repository https://github.com/ocaml/opam-repository/pull/15852 .
